In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
import random
import string

In [ ]:
dictionary = (pd.read_csv('/content/drive/My Drive/Test/HW2/3/dictionary.csv', header = None)).to_numpy()
coded_words = (pd.read_csv('/content/drive/My Drive/Test/HW2/3/coded_words.csv', header = None)).to_numpy()

In [ ]:
def decode(key, coded_words):
  alphabet = list(string.ascii_lowercase)
  keys = dict(zip(key, alphabet))
  size = (coded_words.shape)[0]
  encoded_words = []
  for i in range(size):
    s = ''
    for char in coded_words[i, 0]:
      s += keys.get(char, char)
    encoded_words.append(s)
  return encoded_words

In [ ]:
def fitting_function(population, dictionary, coded_words):
  size = len(population)
  fit_count = np.zeros(size)
  for i in range(size):
    encoded_words = decode(population[i], coded_words)
    for j in range(101):
      if np.any(encoded_words[j] == dictionary[:, 0]):
        fit_count[i] += 1
  return fit_count

In [ ]:
def crossover(chro1, chro2):
  help = chro1[:13]
  chro1[:13] = chro2[:13]
  chro2[:13] = help
  alphabet = list(string.ascii_lowercase)
  while (True):
    for i in alphabet:
      if chro1.count(i) != 1 and chro1.count(i) != 0:
        indx = chro1.index(i)
        r_indx = random.randint(0, 25)
        chro1[indx] = chro2[r_indx]
        chro2[r_indx] = i
    count = 0
    for i in alphabet:
      if chro1.count(i) == 1:
        count += 1
    if count == 26:
      break
  return

In [ ]:
def mutation(chro):
  indx1 = random.randint(0, 25)
  indx2 = random.randint(0, 25)
  help = chro[indx1]
  chro[indx1] = chro[indx2]
  chro[indx2] = help
  return

In [ ]:
def selection(population, fit_count, dictionary, coded_words):
  size = (fit_count.shape)[0]
  indxs = (np.argpartition(fit_count, size - 1))
  p1 = (random.choices(population, fit_count))[0]
  p2 = (random.choices(population, fit_count))[0]
  crossover(p1, p2)
  temp = p1
  temp.append(p2)
  f = fitting_function(temp, dictionary, coded_words)
  if f[0] > f[1]:
    c = p1
  else:
    c = p2
  population[indxs[0]] = c
  p = random.choice(population)
  mutation(p)
  return

In [ ]:
population = []
for i in range(26):
  population.append((list(string.ascii_lowercase)))
  random.shuffle(population[i])
fit_count = fitting_function(population, dictionary, coded_words)
indxs = (np.nonzero(fit_count))[0]
fit_count = fit_count[indxs]
t = []
for i in range(len(indxs)):
  t.append(population[int(indxs[i])])
population = t
while (True):
  print(fit_count)
  if any(fit_count == 101):
    break
  selection(population, fit_count, dictionary, coded_words)
  fit_count = fitting_function(population, dictionary, coded_words)
print(population[(np.where(fit_count == 101))[0]])

[1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 2. 2. 1.]
[0. 2. 0. 1. 1. 3. 1. 1. 1. 1. 2. 0. 1. 2. 1.]
[0. 2. 0. 1. 1. 3. 1. 1. 1. 0. 2. 0. 1. 2. 1.]
[1. 1. 0. 1. 0. 3. 1. 1. 1. 0. 2. 0. 1. 2. 1.]
